#!/bin/sh

## ENVIRONMENT

# fix Java applications
export _JAVA_AWT_WM_NONREPARENTING=1

## DECIDE MONITORSETUP

monitorsetup=$(echo -e "mobile\nwith_dock" | dmenu -i -p "Choose a monitor setup:")

## MONITORS

case $monitorsetup in
  with_dock)
    ~/.screenlayout/with_dock.sh
    bspc monitor eDP-1 -r
    bspc monitor DP-1-1 -d s d f
    bspc monitor DP-1-3 -d w e r
    ;;
  mobile|*)
    ~/.screenlayout/mobile.sh
    bspc monitor eDP-1 -d s d f w e r
    ;;
esac

## UTILITIES

# start sxhkd
killall -q sxhkd
sxhkd &

# set cursor
xsetroot -cursor_name left_ptr &

# start polybar
killall -q polybar
case $monitorsetup in
  with_dock)
    polybar mybar_DP-1-1 &
    polybar mybar_DP-1-3 &
    ;;
  mobile|*)
    polybar mybar_full &
    ;;
esac

# start nm-applet
killall -q nm-applet
nm-applet &

# start pasystray
killall -q pasystray
pasystray &

# start blueman-applet
killall -q blueman-applet
blueman-applet &

# start clipmenud
killall -q clipmenud
clipmenud &

# optionally start ferdi
~/.scripts/dmenu_no_yes.sh 'Start ferdi?' 'ferdi' &

## BSPWM CONFIG

# general
bspc config window_gap 4
bspc config border_width 2
bspc config top_padding 19
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config normal_border_color "#333333" 
bspc config focused_border_color "#ffdd00" 
bspc config active_border_color "#fff6ba"
bspc config presel_feedback_color "#ffee82"

# tiled layout
bspc config split_ratio 0.5

# monocle layout
bspc config borderless_monocle true
bspc config gapless_monocle true

## BSPWM RULES

bspc rule -a Ferdi desktop='^6'
bspc rule -a Emacs state=tiled
